# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.11
jobs:
  build:
    docker:
      - image: circleci/node:10.12-browsers

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      # run build!
      - run: yarn build
      # run linter!
      - run: yarn lint
      # run tests!
      - run: yarn test

      - run: npx semantic-release

      - run:
          name: SETTING_ENV
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then
            echo "export S3_BUCKET=$DEV_S3_BUCKET"
            else
            echo "export S3_BUCKET=$DEV_S3_BUCKET"
            fi

      - run: echo "TEST ECHO"
      - run: echo $DEV_S3_BUCKET
      - run: echo ${DEV_S3_BUCKET}
      - run: echo ${S3_BUCKET}
      - run: echo $S3_BUCKET

      - aws-s3/sync:
          from: build
          to: 's3://dev-minoto-web/'
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          overwrite: true

