name: Minoto-WEB

on:
  push:
    branches:
      - beta

jobs:
  minoto-web-beta-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "10.12"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Run Build
        run: yarn build
      - name: Run Linter
        run: yarn lint
      - name: Run Test
        run: yarn test
      # - name: Run Cypress
      #   run: yarn ci:cypress-run
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: beta-minoto-com
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
          AWS_REGION: "eu-central-1" # optional: defaults to us-east-1
    #  - name: Run Symantic Release
    #    run: npx semantic-release
#AKIA454PXTKS3PYXLFWK  dvWq/dDkLBIfGJwx0FV4YAs7L2OVKztWKxhuCqmY
